export const guideStaticPages:string[][] = [
    [
        "basic-concepts",
        "big-o"
    ],
    [
        "basic-concepts",
        "logic"
    ],
    [
        "basic-concepts",
        "operators"
    ],
    [
        "basic-concepts",
        "cpp-syntax"
    ],
    [
        "data-structures",
        "iterators"
    ],
    [
        "data-structures",
        "array"
    ],
    [
        "data-structures",
        "list"
    ],
    [
        "data-structures",
        "set"
    ],
    [
        "data-structures",
        "stack"
    ],
    [
        "data-structures",
        "queue"
    ],
    [
        "data-structures",
        "map"
    ],
    [
        "dynamic-programming",
        "optimization"
    ],
    [
        "dynamic-programming",
        "approaches"
    ],
    [
        "dynamic-programming",
        "knapsack"
    ],
    [
        "dynamic-programming",
        "grid"
    ],
    [
        "dynamic-programming",
        "lis"
    ],
    [
        "dynamic-programming",
        "bitmask"
    ],
    [
        "dynamic-programming",
        "range"
    ],
    [
        "dynamic-programming",
        "digit"
    ],
    [
        "general-algorithms",
        "sorting"
    ],
    [
        "general-algorithms",
        "searching"
    ],
    [
        "graph-theory",
        "forms"
    ],
    [
        "graph-theory",
        "traversal"
    ],
    [
        "graph-theory",
        "connected-components"
    ],
    [
        "graph-theory",
        "min-max-spanning-tree"
    ],
    [
        "graph-theory",
        "cycles"
    ],
    [
        "graph-theory",
        "shortest-path"
    ],
    [
        "graph-theory",
        "topological-order"
    ],
    [
        "graph-theory",
        "bipartition"
    ],
    [
        "graph-theory",
        "flow"
    ],
    [
        "math",
        "bit-manipulation"
    ],
    [
        "math",
        "combinatorics"
    ],
    [
        "math",
        "geometry"
    ],
    [
        "math",
        "modular-arithmetic"
    ],
    [
        "math",
        "number-theory"
    ],
    [
        "querying",
        "structures"
    ],
    [
        "querying",
        "range-queries"
    ],
    [
        "querying",
        "point-update-point-query"
    ],
    [
        "querying",
        "point-update-range-query"
    ],
    [
        "querying",
        "range-update-point-query"
    ],
    [
        "querying",
        "range-update-range-query"
    ],
    [
        "trees",
        "traversal"
    ],
    [
        "trees",
        "diameter"
    ],
    [
        "trees",
        "subtrees"
    ],
    [
        "trees",
        "binary-tree"
    ],
    [
        "trees",
        "lowest-common-ancestor"
    ],
    [
        "trees",
        "decompositions"
    ],
    [
        "data-structures",
        "queue",
        "priority-queue"
    ],
    [
        "data-structures",
        "set",
        "multiset"
    ],
    [
        "data-structures",
        "set",
        "ordered-set"
    ],
    [
        "general-algorithms",
        "searching",
        "binary-search"
    ],
    [
        "general-algorithms",
        "sorting",
        "bubble-sort"
    ],
    [
        "general-algorithms",
        "sorting",
        "insertion-sort"
    ],
    [
        "general-algorithms",
        "sorting",
        "merge-sort"
    ],
    [
        "general-algorithms",
        "sorting",
        "quick-sort"
    ],
    [
        "graph-theory",
        "connected-components",
        "dsu"
    ],
    [
        "graph-theory",
        "connected-components",
        "kosarajus"
    ],
    [
        "graph-theory",
        "flow",
        "ford-fulkerson"
    ],
    [
        "graph-theory",
        "forms",
        "undirected"
    ],
    [
        "graph-theory",
        "forms",
        "directed"
    ],
    [
        "graph-theory",
        "min-max-spanning-tree",
        "kruskals"
    ],
    [
        "graph-theory",
        "min-max-spanning-tree",
        "prims"
    ],
    [
        "graph-theory",
        "shortest-path",
        "dijkstras"
    ],
    [
        "graph-theory",
        "shortest-path",
        "bellman-ford"
    ],
    [
        "graph-theory",
        "shortest-path",
        "floyd-warshall"
    ],
    [
        "graph-theory",
        "traversal",
        "dfs"
    ],
    [
        "graph-theory",
        "traversal",
        "bfs"
    ],
    [
        "querying",
        "structures",
        "sparse-table"
    ],
    [
        "querying",
        "structures",
        "segment-tree"
    ],
    [
        "querying",
        "structures",
        "fenwick-tree"
    ],
    [
        "trees",
        "decompositions",
        "heavy-light"
    ],
    [
        "trees",
        "traversal",
        "preorder"
    ],
    [
        "trees",
        "traversal",
        "inorder"
    ],
    [
        "trees",
        "traversal",
        "postorder"
    ]
];