export const tags = [
    "bellman-ford",
    "binary search",
    "binary tree",
    "bipartite",
    "bitmask",
    "bounding",
    "brute force",
    "connected components",
    "combinatorics",
    "constructive",
    "cycles",
    "dijkstra's",
    "divide and conquer",
    "dp",
    "dpendence",
    "data structures",
    "fenwick tree",
    "flood fill",
    "game",
    "geometry",
    "graph",
    "graph modeling",
    "greedy",
    "high-low decomposition",
    "implementation",
    "k shortest paths",
    "knapsack",
    "lis",
    "math",
    "modular arithmetic",
    "number theory",
    "ordered adding",
    "ordered set",
    "path reconstruction",
    "precision",
    "prefix sum",
    "query",
    "strongly connected components",
    "segment tree",
    "sorting",
    "shortest paths",
    "string",
    "subsequence",
    "topological ordering",
    "traversal",
    "tree",
    "two pointers",
];