export const topics = [
    { name: "Basic Concepts",
        short: "Basic",
        href: "/basic-concepts", 
        color: "#d92632",
        subtopics: ["Big O", "Logic"],
        subsub: [[], []], },

    { name: "Data Structures", 
        short: "DS",
        href: "/data-structures", 
        color: "#933310",
        subtopics: ["Array", "List", "Set", "Stack", "Queue", "Map"],
        subsub: [[], [], ["Multiset", "Ordered Set"], [], ["Priority Queue"], []],},

    { name: "General Algorithms", 
        short: "Algs",
        href: "/general-algorithms", 
        color: "#EC5809",
        subtopics: ["Sorting", "Searching"],
        subsub: [["Bubble Sort", "Insertion Sort", "Merge Sort", "Quick Sort"], ["Binary Search"]], },

    { name: "Math", 
        short: "Math",
        href: "/math", 
        color: "#6D4BDC",
        subtopics: ["Bit Manipulation", "Combinatorics", "Geometry", "Modular Arithmetic", "Number Theory"],
        subsub: [[], [], [], [], []], },

    { name: "Dynamic Programming", 
        short: "DP",
        href: "/dynamic-programming", 
        color: "#DB67BE",
        subtopics: ["Optimization", "Approaches", "Knapsack", "Grid", "LIS", "Bitmask", "Range", "Digit"],
        subsub: [[], [], [], [], [], [], [], []], },

    { name: "Graph Theory", 
        short: "Graphs",
        href: "/graph-theory", 
        color: "#53A754",
        subtopics: ["Forms", "Traversal", "Connected Components", "Min/Max Spanning Tree", "Cycles", "Shortest Path", "Topological Order", "Bipartition", "Flow"],
        subsub: [["Undirected", "Directed"], ["DFS", "BFS"], ["DSU", "Kosaraju's"], ["Kruskal's", "Prim's"], [], ["Dijkstra's", "Bellman-Ford", "Floyd-Warshall"], [], [], ["Ford-Fulkerson"]], },

    { name: "Trees", 
        short: "Trees",
        href: "/trees", 
        color: "#f99f3e",
        subtopics: ["Traversal", "Diameter", "Subtrees", "Binary Tree", "Lowest Common Ancestor", "Decompositions"],
        subsub: [["Preorder", "Inorder", "Postorder"], [], [], [], [], ["Heavy-Light"]], },

    { name: "Querying", 
        short: "Query",
        href: "/querying", 
        color: "#3884ff",
        subtopics: ["Structures", "Range Queries", "Point Update Point Query", "Point Update Range Query", "Range Update Point Query", "Range Update Range Query"],
        subsub: [["Sparse Table", "Segment Tree", "Fenwick Tree (BIT)"], [], [], [], [], []], },
];