export const topics = [
    { name: "Basic Concepts",
        short: "Basic",
        slug: "basic-concepts",
        color: "#d92632",
        subtopics: ["Big O", "Logic"],
        subtopicSlugs: ["big-o", "logic"],
        subsub: [[], []],
        subsubSlugs: [[], []], },

    { name: "Data Structures", 
        short: "DS",
        slug: "data-structures",
        color: "#933310",
        subtopics: ["Array", "List", "Set", "Stack", "Queue", "Map"],
        subtopicSlugs: ["array", "list", "set", "stack", "queue", "map"],
        subsub: [[], [], ["Multiset", "Ordered Set"], [], ["Priority Queue"], []],
        subsubSlugs: [[], [], ["multiset", "ordered-set"], [], ["priority-queue"], []],},

    { name: "General Algorithms", 
        short: "Algs",
        slug: "general-algorithms",
        color: "#EC5809",
        subtopics: ["Sorting", "Searching"],
        subtopicSlugs: ["sorting", "searching"],
        subsub: [["Bubble Sort", "Insertion Sort", "Merge Sort", "Quick Sort"], ["Binary Search"]],
        subsubSlugs: [["bubble-sort", "insertion-sort", "merge-sort", "quick-sort"], ["binary-search"]], },

    { name: "Math", 
        short: "Math",
        slug: "math",
        color: "#6D4BDC",
        subtopics: ["Bit Manipulation", "Combinatorics", "Geometry", "Modular Arithmetic", "Number Theory"],
        subtopicSlugs: ["bit-manipulation", "combinatorics", "geometry", "modular-arithmetic", "number-theory"],
        subsub: [[], [], [], [], []],
        subsubSlugs: [[], [], [], [], []], },

    { name: "Dynamic Programming", 
        short: "DP",
        slug: "dynamic-programming",
        color: "#DB67BE",
        subtopics: ["Optimization", "Approaches", "Knapsack", "Grid", "LIS", "Bitmask", "Range", "Digit"],
        subtopicSlugs: ["optimization", "approaches", "knapsack", "grid", "lis", "bitmask", "range", "digit"],
        subsub: [[], [], [], [], [], [], [], []],
        subsubSlugs: [[], [], [], [], [], [], [], []], },

    { name: "Graph Theory", 
        short: "Graphs",
        slug: "graph-theory",
        color: "#53A754",
        subtopics: ["Forms", "Traversal", "Connected Components", "Min/Max Spanning Tree", "Cycles", "Shortest Path", "Topological Order", "Bipartition", "Flow"],
        subtopicSlugs: ["forms", "traversal", "connected-components", "min-max-spanning-tree", "cycles", "shortest-path", "topological-order", "bipartition", "flow"],
        subsub: [["Undirected", "Directed"], ["DFS", "BFS"], ["DSU", "Kosaraju's"], ["Kruskal's", "Prim's"], [], ["Dijkstra's", "Bellman-Ford", "Floyd-Warshall"], [], [], ["Ford-Fulkerson"]],
        subsubSlugs: [["undirected", "directed"], ["dfs", "bfs"], ["dsu", "kosarajus"], ["kruskals", "prims"], [], ["dijkstras", "bellman-ford", "floyd-warshall"], [], [], ["ford-fulkerson"]], },

    { name: "Trees", 
        short: "Trees",
        slug: "trees",
        color: "#f99f3e",
        subtopics: ["Traversal", "Diameter", "Subtrees", "Binary Tree", "Lowest Common Ancestor", "Decompositions"],
        subtopicSlugs: ["traversal", "diameter", "subtrees", "binary-tree", "lowest-common-ancestor", "decompositions"],
        subsub: [["Preorder", "Inorder", "Postorder"], [], [], [], [], ["Heavy-Light"]],
        subsubSlugs: [["preorder", "inorder", "postorder"], [], [], [], [], ["heavy-light"]], },

    { name: "Querying", 
        short: "Query",
        slug: "querying",
        color: "#3884ff",
        subtopics: ["Structures", "Range Queries", "Point Update Point Query", "Point Update Range Query", "Range Update Point Query", "Range Update Range Query"],
        subtopicSlugs: ["structures", "range-queries", "point-update-point-query", "point-update-range-query", "range-update-point-query", "range-update-range-query"],
        subsub: [["Sparse Table", "Segment Tree", "Fenwick Tree (BIT)"], [], [], [], [], []],
        subsubSlugs: [["sparse-table", "segment-tree", "fenwick-tree"], [], [], [], [], []] },
];