export const topics = [
    { name: "Basic Concepts",
        short: "Basic",
        slug: "basic-concepts",
        href: "/training/basic-concepts/big-o",
        color: "#d92632",
        subtopics: ["Big O", "Logic"], },

    { name: "Data Structures", 
        short: "DS",
        slug: "data-structures",
        href: "/training/data-structures/iterators",
        color: "#933310",
        subtopics: ["Array", "List", "Set", "Stack", "Queue", "Map"], },

    { name: "General Algorithms", 
        short: "Algs",
        slug: "general-algorithms",
        href: "/training/general-algorithms/sorting",
        color: "#EC5809",
        subtopics: ["Sorting", "Searching"], },

    { name: "Math", 
        short: "Math",
        slug: "math",
        href: "/training/math/bit-manipulation",
        color: "#6D4BDC",
        subtopics: ["Bit Manipulation", "Combinatorics", "Geometry", "Modular Arithmetic", "Number Theory"], },

    { name: "Dynamic Programming", 
        short: "DP",
        slug: "dynamic-programming",
        href: "/training/dynamic-programming/optimization",
        color: "#DB67BE",
        subtopics: ["Optimization", "Approaches", "Knapsack", "Grid", "LIS", "Bitmask", "Range", "Digit"], },

    { name: "Graph Theory", 
        short: "Graphs",
        slug: "graph-theory",
        href: "/training/graph-theory/forms",
        color: "#53A754",
        subtopics: ["Forms", "Traversal", "Connected Components", "Min/Max Spanning Tree", "Cycles", "Shortest Path", "Topological Order", "Bipartition", "Flow"], },

    { name: "Trees", 
        short: "Trees",
        slug: "trees",
        href: "/training/trees/traversal",
        color: "#f99f3e",
        subtopics: ["Traversal", "Diameter", "Subtrees", "Binary Tree", "Lowest Common Ancestor", "Decompositions"], },

    { name: "Querying", 
        short: "Query",
        slug: "querying",
        href: "/training/querying/structures",
        color: "#3884ff",
        subtopics: ["Structures", "Range Queries", "Point Update Point Query", "Point Update Range Query", "Range Update Point Query", "Range Update Range Query"], },
];