import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

const chillax = localFont({
  src: '../public/fonts/Chillax-Variable.ttf',
  variable: '--font-chillax',
  weight: "100 900",
});

const outfit = localFont({
  src: '../public/fonts/Outfit-Variable.ttf',
  variable: '--font-outfit',
  weight: "100 900",
});

const hind = localFont({
  src: '../public/fonts/Hind-Variable.ttf',
  variable: '--font-hind',
  weight: "100 900",
});

const author = localFont({
  src: '../public/fonts/Author-Variable.ttf',
  variable: '--font-author',
  weight: "100 900",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chillax.variable} ${outfit.variable} ${author.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
